config/routes.rb
RankAppV2::Application.routes.draw do
  get "grandtotal/index"

  resources :newtasks

  get "main_up_task/index"

  get "rank/index"

  resources :upcoming_tasks

  get "home/index"

  resources :masters

   root :to => "home#index"

end

app/models/newtask.rb
class Newtask < ActiveRecord::Base
end

app/controllers/newtasks_controller.rb
class NewtasksController < ApplicationController
  # GET /newtasks
  # GET /newtasks.xml
  def index
    @newtasks = Newtask.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @newtasks }
    end
  end

  # GET /newtasks/1
  # GET /newtasks/1.xml
  def show
    @newtask = Newtask.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @newtask }
    end
  end

  # GET /newtasks/new
  # GET /newtasks/new.xml
  def new
    @newtask = Newtask.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @newtask }
    end
  end

  # GET /newtasks/1/edit
  def edit
    @newtask = Newtask.find(params[:id])
  end

  # POST /newtasks
  # POST /newtasks.xml
  def create
    @newtask = Newtask.new(params[:newtask])

    respond_to do |format|
      if @newtask.save
        format.html { redirect_to(@newtask, :notice => 'Newtask was successfully created.') }
        format.xml  { render :xml => @newtask, :status => :created, :location => @newtask }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @newtask.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /newtasks/1
  # PUT /newtasks/1.xml
  def update
    @newtask = Newtask.find(params[:id])

    respond_to do |format|
      if @newtask.update_attributes(params[:newtask])
        format.html { redirect_to(@newtask, :notice => 'Newtask was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @newtask.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /newtasks/1
  # DELETE /newtasks/1.xml
  def destroy
    @newtask = Newtask.find(params[:id])
    @newtask.destroy

    respond_to do |format|
      format.html { redirect_to(newtasks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/newtasks_helper.rb
module NewtasksHelper
end

app/views/newtasks/_form.html.erb
<%= form_for(@newtask) do |f| %>
  <% if @newtask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newtask.errors.count, "error") %> prohibited this newtask from being saved:</h2>

      <ul>
      <% @newtask.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :timeduration %><br />
    <%= f.text_field :timeduration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newtasks/edit.html.erb
<h1>Editing newtask</h1>

<%= render 'form' %>

<%= link_to 'Show', @newtask %> |
<%= link_to 'Back', newtasks_path %>

app/views/newtasks/index.html.erb
<h1>Listing newtasks</h1>

<table>
  <tr>
    <th>Task</th>
    <th>Timeduration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @newtasks.each do |newtask| %>
  <tr>
    <td><%= newtask.task %></td>
    <td><%= newtask.timeduration %></td>
    <td><%= link_to 'Show', newtask %></td>
    <td><%= link_to 'Edit', edit_newtask_path(newtask) %></td>
    <td><%= link_to 'Destroy', newtask, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Newtask', new_newtask_path %>

app/views/newtasks/new.html.erb
<h1>New newtask</h1>

<%= render 'form' %>

<%= link_to 'Back', newtasks_path %>

app/views/newtasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task:</b>
  <%= @newtask.task %>
</p>

<p>
  <b>Timeduration:</b>
  <%= @newtask.timeduration %>
</p>


<%= link_to 'Edit', edit_newtask_path(@newtask) %> |
<%= link_to 'Back', newtasks_path %>