config/routes.rb
RankAppV2::Application.routes.draw do
  get "grandtotal/index"

  resources :newtasks

  get "main_up_task/index"

  get "rank/index"

  resources :upcoming_tasks

  get "home/index"

  resources :masters

   root :to => "home#index"

end

app/models/master.rb
class Master < ActiveRecord::Base
	attr_accessible :e_name, :task, :startdate, :enddate, 
			:points, :comment

	validates :e_name, :presence => true
	validates :startdate, :presence => true
	validates :enddate, :presence => true
#	validates :points, :presence => true
	validates_numericality_of :points, :only_integer => true, :message => "can only be whole number and can't be blank."
	validates :task, :presence => true
	
end

app/controllers/masters_controller.rb
require 'digest/md5'

class MastersController < ApplicationController
  
  USERS = {"admin" => "password123"}  # username: admin password: password

  before_filter :authenticate

  # GET /masters
  # GET /masters.xml
  def index
    m = Master.select("*")
	@masters = m.order("e_name asc")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @masters }

      a1= Master.select("e_name as name, sum(points) as points").group("e_name")
      a = a1.order("points DESC")
      @b = a.all
    end

  end

  # GET /masters/1
  # GET /masters/1.xml
  def show
    @master = Master.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @master }
    end
  end

  # GET /masters/new
  # GET /masters/new.xml
  def new
    @master = Master.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @master }
    end
  end

  # GET /masters/1/edit
  def edit
    @master = Master.find(params[:id])
  end

  # POST /masters
  # POST /masters.xml
  def create
    @master = Master.new(params[:master])

    respond_to do |format|
      if @master.save
        format.html { redirect_to(@master, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @master, :status => :created, :location => @master }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @master.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /masters/1
  # PUT /masters/1.xml
  def update
    @master = Master.find(params[:id])

    respond_to do |format|
      if @master.update_attributes(params[:master])
        format.html { redirect_to(@master, :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @master.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /masters/1
  # DELETE /masters/1.xml
  def destroy
    @master = Master.find(params[:id])
    @master.destroy

    respond_to do |format|
      format.html { redirect_to(masters_url) }
      format.xml  { head :ok }
    end
  end
	
 private
    def authenticate
      authenticate_or_request_with_http_digest() do |username|
        USERS[username]
      end
    end

end

app/helpers/masters_helper.rb
module MastersHelper
end

app/views/masters/_form.html.erb
<%= form_for(@master) do |f| %>
  <% if @master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@master.errors.count, "error") %> prohibited this master from being saved:</h2>

      <ul>
      <% @master.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :e_name %><br />
    <%= f.text_field :e_name %>
  </div>
  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br />
    <%= f.date_select :enddate %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.text_field :points %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/masters/edit.html.erb
<h1>Editing master</h1>

<%= render 'form' %>

<%= link_to 'Show', @master %> |
<%= link_to 'Back', masters_path %>

app/views/masters/index.html.erb
<h1 align = "center"><i>Assigned Tasks</i></h1>

<table align = "center" width = "80%">
  <tr>
    <th>E name</th>
    <th>Task</th>
    <th>Startdate</th>
    <th>Enddate</th>
    <th>Points</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @masters.each do |master| %>
  <tr>
    <td align = "center"><%= master.e_name %></td>
    <td align = "center"><%= master.task %></td>
    <td align = "center"><%= master.startdate %></td>
    <td align = "center"><%= master.enddate %></td>
    <td align = "center"><%= master.points %></td>
    <td align = "center"><%= master.comment %></td>
    <td align = "center"><%= link_to 'Show', master %></td>
    <td align = "center"><%= link_to 'Edit', edit_master_path(master) %></td>
    <td align = "center"><%= link_to 'Destroy', master, :confirm => 'Do you want to delete this task?', :method => :delete %></td>
  </tr>
<% end %>
</table>



<br />

<%= link_to 'Assign New Task', new_master_path %>

<p>
  <a href="/upcoming_tasks">Edit Upcoming Tasks</a>
</p>


<p>
  <a href="/grandtotal/index">Check Grand total of points of all employees</a>
</p>

app/views/masters/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', masters_path %>

app/views/masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>E name:</b>
  <%= @master.e_name %>
</p>

<p>
  <b>Task:</b>
  <%= @master.task %>
</p>

<p>
  <b>Startdate:</b>
  <%= @master.startdate %>
</p>

<p>
  <b>Enddate:</b>
  <%= @master.enddate %>
</p>

<p>
  <b>Points:</b>
  <%= @master.points %>
</p>

<p>
  <b>Comment:</b>
  <%= @master.comment %>
</p>


<%= link_to 'Edit', edit_master_path(@master) %> |
<%= link_to 'Back', masters_path %>