config/routes.rb
RankAppV2::Application.routes.draw do
  get "grandtotal/index"

  resources :newtasks

  get "main_up_task/index"

  get "rank/index"

  resources :upcoming_tasks

  get "home/index"

  resources :masters

   root :to => "home#index"

end

app/models/upcoming_task.rb
class UpcomingTask < ActiveRecord::Base
	attr_accessible :task, :TimeDuration

	validates :task, :presence => true
	validates :TimeDuration, :presence =>true

end

app/controllers/upcoming_tasks_controller.rb
class UpcomingTasksController < ApplicationController
	 
  USERS = {"admin" => "password123"}  # username: admin password: password

  # GET /upcoming_tasks
  # GET /upcoming_tasks.xml
  def index
    @upcoming_tasks = UpcomingTask.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @upcoming_tasks }
    end
  end

  # GET /upcoming_tasks/1
  # GET /upcoming_tasks/1.xml
  def show
    @upcoming_task = UpcomingTask.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @upcoming_task }
    end
  end

  # GET /upcoming_tasks/new
  # GET /upcoming_tasks/new.xml
  def new
    @upcoming_task = UpcomingTask.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @upcoming_task }
    end
  end

  # GET /upcoming_tasks/1/edit
  def edit
    @upcoming_task = UpcomingTask.find(params[:id])
  end

  # POST /upcoming_tasks
  # POST /upcoming_tasks.xml
  def create
    @upcoming_task = UpcomingTask.new(params[:upcoming_task])

    respond_to do |format|
      if @upcoming_task.save
        format.html { redirect_to(@upcoming_task, :notice => 'Upcoming task was successfully created.') }
        format.xml  { render :xml => @upcoming_task, :status => :created, :location => @upcoming_task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @upcoming_task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /upcoming_tasks/1
  # PUT /upcoming_tasks/1.xml
  def update
    @upcoming_task = UpcomingTask.find(params[:id])

    respond_to do |format|
      if @upcoming_task.update_attributes(params[:upcoming_task])
        format.html { redirect_to(@upcoming_task, :notice => 'Upcoming task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @upcoming_task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /upcoming_tasks/1
  # DELETE /upcoming_tasks/1.xml
  def destroy
    @upcoming_task = UpcomingTask.find(params[:id])
    @upcoming_task.destroy

    respond_to do |format|
      format.html { redirect_to(upcoming_tasks_url) }
      format.xml  { head :ok }
    end
  end

  
 private
    def authenticate
      authenticate_or_request_with_http_digest() do |username|
        USERS[username]
      end
    end

end

app/helpers/upcoming_tasks_helper.rb
module UpcomingTasksHelper
end

app/views/upcoming_tasks/_form.html.erb
<%= form_for(@upcoming_task) do |f| %>
  <% if @upcoming_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upcoming_task.errors.count, "error") %> prohibited this upcoming_task from being saved:</h2>

      <ul>
      <% @upcoming_task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task %><br />
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :TimeDuration %><br />
    <%= f.text_field :TimeDuration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/upcoming_tasks/edit.html.erb
<h1>Editing upcoming_task</h1>

<%= render 'form' %>

<%= link_to 'Show', @upcoming_task %> |
<%= link_to 'Back', upcoming_tasks_path %>

app/views/upcoming_tasks/index.html.erb
<h1 align = "center">Upcoming Tasks</h1>

<table align = "center" width = "40%">
  <tr>
    <th>Task</th>
    <th>Timeduration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @upcoming_tasks.each do |upcoming_task| %>
  <tr>
    <td align = "center"><%= upcoming_task.task %></td>
    <td align = "center"><%= upcoming_task.TimeDuration %></td>
    <td align = "center"><%= link_to 'Show', upcoming_task %></td>
    <td align = "center"><%= link_to 'Edit', edit_upcoming_task_path(upcoming_task) %></td>
    <td align = "center"><%= link_to 'Destroy', upcoming_task, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Upcoming task', new_upcoming_task_path %>


<p>
  <a href="/masters">Go back to admin page</a>
</p>

app/views/upcoming_tasks/new.html.erb
<h1>New upcoming_task</h1>

<%= render 'form' %>

<%= link_to 'Back', upcoming_tasks_path %>

app/views/upcoming_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task:</b>
  <%= @upcoming_task.task %>
</p>

<p>
  <b>Timeduration:</b>
  <%= @upcoming_task.TimeDuration %>
</p>


<%= link_to 'Edit', edit_upcoming_task_path(@upcoming_task) %> |
<%= link_to 'Back', upcoming_tasks_path %>